services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always
    # depends_on:
    #   - db
    env_file:
      - .env
#   db:
#     image: postgres:latest
#     restart: always
#     ports:
#       - "5432:5432"
#     env_file:
#       - .env
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#   adminer:
#     image: adminer
#     depends_on:
#       - db
#     restart: always
#     ports:
#       - 8080:8080
# volumes:
#   postgres_data:
